version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      development-tooling:
        dependency-type: development
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: "@deepseek-ai/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
